HS-237 | Difficulty window
Hotel-Simulator/Hotel-Simulator pull request #103
Opened 2023-11-02 14:40 UTC by dudiiiiiiii

2023-11-02 18:20 UTC, pwgacek approved these changes

2023-11-02 18:20 UTC, pwgacek commented on core/src/main/java/pl/agh/edu/ui/window/DifficultyWindow.java
> +		for (DifficultyLevel level : DifficultyLevel.values()) {
można to zapisać przy użyciu foreach. coś w wstylu:
`Arrays.stream(DifficultyLevel.values()).forEach(level -> buttonsList.add(new DifficultyButton(level)))`
podobnie niżej

2023-11-02 19:41 UTC, lawos98 requested changes

2023-11-02 19:41 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/ui/window/DifficultyWindow.java
> +	private int width;
musimy trzymać te wartości w tej klasie skoro sam aktor ma takie pola

2023-11-02 19:41 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/ui/window/DifficultyWindow.java
> +			largePaddingMultiplier = height / 1000f * 0.85f;
dlaczego przestawiamy tą wartość w przypadku zmiany na LARGE a w przypadku powrotu już np na NORMAL nic nie zmieniamy przez co przed wejściem na LARGE mamy wartość 1 a póżniej po powrocię np 2

2023-11-02 19:41 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/ui/window/DifficultyWindow.java
> +	private TextButton createTextButton(String text, TextButton.TextButtonStyle style) {
ta fukcja ma sens?

2023-11-02 19:41 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/ui/window/DifficultyWindow.java
> +	public void onLanguageChange() {
same case as before

2023-11-02 19:41 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/ui/window/DifficultyWindow.java
> +	public void onResolutionChange() {
same case as before

2023-11-04 16:48 UTC, pwgacek submitted a review, later dismissed

2023-11-06 20:14 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/ui/panel/DifficultyPanel.java
> +		Label.LabelStyle titleLabelStyle = skin.get(getTitleFont(), Label.LabelStyle.class);
to co obgadywaliśmy w tym case wszystkie fonty zmieniają kolor na żółty

2023-11-06 20:15 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/ui/panel/DifficultyPanel.java
> +	public void getSize() {
jak już to setSize()

2023-11-06 20:17 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/ui/panel/DifficultyPanel.java
> +		buttonsList.forEach(button -> frame.add(button).left().padTop((int) (largePaddingMultiplier * frame.getHeight() / 24)).padLeft(frame.getWidth() / 6 + buttonsList.indexOf(
z tymi wszystkimi wartościami bym wyciągnał do statycznej klasy i ograł w niej `largePaddingMultiplier` w zależności od size trochę czytelniej i cała metodologia tam zostaje ale up to you

2023-11-06 20:27 UTC, lawos98 commented
Dodatkowo IMHO usunał bym obwódke czytaj przycisk z Choose Dificulty bo to nie jest przycisk i zastosował bym zwykły customLabel i do tego jeszcze przy rozdzielczościach innych niż 1366x900 , 1920x1080 , 3440x1440 dziwnie formatuje nam się layout szczególnie widać to np 1440x900 albo 2560x1440 ( przyciski Back, Play są w połowie wysokości) może warto by było zastosowac layout z table z wykorzystaniem grow na środkowym poziomie.

2023-11-06 23:12 UTC, dudiiiiiiii commented
> Dodatkowo IMHO usunał bym obwódke czytaj przycisk z Choose Dificulty bo to nie jest przycisk i zastosował bym zwykły customLabel i do tego jeszcze przy rozdzielczościach innych niż 1366x900 , 1920x1080 , 3440x1440 dziwnie formatuje nam się layout szczególnie widać to np 1440x900 albo 2560x1440 ( przyciski Back, Play są w połowie wysokości) może warto by było zastosowac layout z table z wykorzystaniem grow na środkowym poziomie.

2023-11-06 23:18 UTC, dudiiiiiiii commented
Z labelką od tytułu załatwię już na następnym PR. Dodam sobie w skin composerze na innym branchu image żeby nie robić osobnych PR i zaminię następnym razem.

2023-11-07 17:07 UTC, lawos98 approved these changes

2023-11-07 20:44 UTC, merged