HS-236 | Scenarios window
Hotel-Simulator/Hotel-Simulator pull request #104
Opened 2023-11-02 16:01 UTC by dudiiiiiiii

2023-11-02 18:27 UTC, pwgacek submitted a review, later dismissed

2023-11-02 19:35 UTC, lawos98 requested changes

2023-11-02 19:35 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/ui/component/button/ScenarioButton.java
> +		LanguageLabel languageLabel = new LanguageLabel(labelTextPath, labelFont);
może zamiast wybierać font i zmieniać w nim wielkość i jego kolor warto stworzyć jakiś nowy w skin composerze albo od nowa stworzyć tylko w kodzie jak nigdzie nie będziemy go wykorzystywać

2023-11-02 19:35 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/ui/component/button/ScenarioButton.java
> +	public record ScenarioButtonStyle(HotelType hotelType) {
dlaczego tutaj używamy rekordu?

2023-11-02 19:35 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/ui/component/button/ScenarioButton.java
> +        private static final int PAD_TOP_BOTTOM = 30;
*pad_vertical

2023-11-02 19:35 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/ui/component/button/ScenarioButton.java
> +        private static final int PAD_LEFT_RIGHT = 20;
pad_horizontal

2023-11-02 19:35 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/ui/component/button/ScenarioButton.java
> +	public void onResolutionChange() {
nie jest spoko nadpisywanie tej metody, jak już to chociaż użyć super albo ustawić tą fukcję za pomocą resolutionChangeHandler()

2023-11-02 19:35 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/ui/component/button/ScenarioButton.java
> +		labelStyle.fontColor = SkinColor.ALERT.getColor(SkinColor.ColorLevel._500);
statyczny import x2

2023-11-02 19:35 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/ui/component/button/ScenarioButton.java
> +		this.button = new Button(skin.get("scenario-difficulty-button", Button.ButtonStyle.class));
są też inne konstruktory buttona, takie wygodniejsze w użyciu

2023-11-02 19:35 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/ui/component/button/ScenarioButton.java
> +		button.add(titleLabel).width(5 * width / 24).height(height / 12).row();
niektóre wartości pojawiają się kiluktornie może warto wykrestrakować je do innej metody jeżeli są ze sobą zkorelowane

2023-11-02 19:35 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/ui/component/button/ScenarioButton.java
> +	private int width;
same case jak wcześniej

2023-11-02 19:35 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/ui/frame/TestFrame.java
>  	}
dlla wygody na przyszłość nie zmieniałbym nic w tej klasie jeżeli nie chcemy z niej korzystać, nie będziemy musieli martwić się o konflikty

2023-11-02 19:35 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/ui/window/scenarios/ScenarioWindow.java
> +	public final List<ScenarioButton> buttonsList = new ArrayList<>();
+1

2023-11-02 19:35 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/ui/window/scenarios/ScenarioWindow.java
> +	public final Table frame = new Table();
WrapperTable jak coś też istnieje

2023-11-02 19:35 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/ui/window/scenarios/ScenarioWindow.java
> +			largePaddingMultiplier = height / 1000f * 0.85f;
same case as before

2023-11-02 19:35 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/ui/window/scenarios/ScenarioWindow.java
> +		if (GraphicConfig.getResolution().SIZE.equals(Size.LARGE)) {
statyczny import

2023-11-02 19:35 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/ui/window/scenarios/ScenarioWindow.java
> +			largePaddingMultiplier = height / 1000f * 0.85f;
a jak już może warto te mnożniki wyciągnąć do styli

2023-11-02 19:35 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/ui/window/scenarios/ScenarioWindow.java
> +		titleLabelStyle.fontColor = SkinColor.ALERT.getColor(SkinColor.ColorLevel._500);
same case as before

2023-11-02 19:35 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/ui/component/button/ScenarioButton.java
> +	private final Button button;
może warto trzymać ScenarioButtonStyle jako statyczną klase a nie jako pole

2023-11-02 19:41 UTC, lawos98 requested changes

2023-11-02 19:41 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/ui/window/scenarios/ScenarioWindow.java
> +		frame.debug();
debug

2023-11-03 22:50 UTC, dudiiiiiiii commented on core/src/main/java/pl/agh/edu/ui/component/button/ScenarioButton.java
> +	public record ScenarioButtonStyle(HotelType hotelType) {
Bo w klasie statycznej nie ustawię pola a tak musiałbym do metod przekazywać hotelType

2023-11-03 23:39 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/ui/component/button/ScenarioButton.java
> +	public record ScenarioButtonStyle(HotelType hotelType) {
ale przecież nie musimy tworzyć takiego pola w klasie stylow możemy spokojnie mieć je w klasie nadrzędnej i korzystać z niej w klasie podrzędnej

2023-11-03 23:45 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/ui/component/button/ScenarioButton.java
> +	private Label.LabelStyle createLabelStyle(String labelFont, int lineHeight) {
tak jak pisałem wczęsniej ten sposób jest niezbyt spoko bo wszystkie fonty korzystające z tej wielkości np H4 są nadpisywane i wszystkie jest żółte

2023-11-03 23:48 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/ui/component/button/ScenarioButton.java
> +	private Label.LabelStyle createLabelStyle(String labelFont, int lineHeight) {
tak jak pisałem wczęsniej ten sposób jest niezbyt spoko bo wszystkie fonty korzystające z tej wielkości np H4 są nadpisywane i wszystkie jest żółte

2023-11-04 16:46 UTC, pwgacek submitted a review, later dismissed

2023-11-07 17:07 UTC, lawos98 approved these changes

2023-11-07 20:44 UTC, merged