Hs 166
Hotel-Simulator/Hotel-Simulator pull request #106
Opened 2023-11-03 09:19 UTC by jagodek

2023-11-04 16:43 UTC, pwgacek commented
Nie ma połączenia backendu z frontendem. To będzie w innym pr?

2023-11-04 16:45 UTC, pwgacek requested changes

2023-11-04 16:45 UTC, pwgacek commented on core/src/main/java/pl/agh/edu/engine/bank/BankAccount.java
> +	public String bankDataId;
ja bym zmienił na bankId

2023-11-04 16:45 UTC, pwgacek commented on core/src/main/java/pl/agh/edu/data/type/BankData.java
> +        String id,
może id jako int albo long?

2023-11-04 16:45 UTC, pwgacek commented on core/src/main/java/pl/agh/edu/engine/bank/BankAccount.java
> +	public void setAccountDetails(BankData bankData) {
ja bym zmienił nazwe na setBankData

2023-11-04 16:45 UTC, pwgacek commented on assets/i18n/language_en.properties
> +bank.name.1 = Bank of the World
nie miało być 3 ofert?

2023-11-05 09:54 UTC, jagodek commented
> Nie ma połączenia backendu z frontendem. To będzie w innym pr?

No właśnie czekam jak się Kuba w tej sprawie wypowie. Na razie zrobiłem połączenie tylko ze swoim komponentem.

2023-11-06 11:29 UTC, dudiiiiiiii commented on core/src/main/java/pl/agh/edu/ui/component/bankOffer/BankOffer.java
> +		String valueColor = SkinColor.GRAY.getName(SkinColor.ColorLevel._700);
Tu są jeszcze 2 statyczne importy do zrobienia

2023-11-06 11:29 UTC, dudiiiiiiii commented on core/src/main/java/pl/agh/edu/ui/component/bankOffer/BankOffer.java
> +		innerTable.setTouchable(Touchable.enabled);
To też jest enum więc chyba można statyczny import

2023-11-24 19:36 UTC, closed without merging