HS-253 | RoomBreakingOpinionBucket fix
Hotel-Simulator/Hotel-Simulator pull request #109
Opened 2023-11-04 12:43 UTC by pwgacek

2023-11-04 18:04 UTC, lawos98 requested changes

2023-11-04 18:04 UTC, lawos98 commented on assets/i18n/language_en.properties
> +opinionComment.roomBreaking.brokeAndNotRepaired = There was a minor glitch, and it was not repaired.
glitch ? xD, jak już to malfunction albo defect i chyba bardziej coś w tym stylu by pasowało "We received a room with a small defect and it was not repaired."

2023-11-05 10:49 UTC, lawos98 approved these changes

2023-11-06 09:01 UTC, dudiiiiiiii approved these changes

2023-11-06 12:36 UTC, merged