HS-134
Hotel-Simulator/Hotel-Simulator pull request #11
Opened 2023-08-14 15:16 UTC by pwgacek

dodano obsługę recepcjonistów - Klient idzie teraz do kolejki i czeka na obsługę a nie od razu dostaje albo nie dostaje pokój. Jak za długo czeka (koło 40 min) to opuszcza kolejkę.

2023-08-14 16:20 UTC, lawos98 requested changes

2023-08-14 16:20 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/management/employee/work_scheduler/ReceptionScheduler.java
> +            room.setState(RoomState.FAULT); // todo zmienic na isFault()
TODO zostało

2023-08-14 16:20 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/management/employee/work_scheduler/ReceptionScheduler.java
> +                        if(random.nextDouble() < JSONGameDataLoader.roomFaultProbability){
to można wrzucić do jakiegoś utils żeby czesto nie powtarzać

2023-08-14 16:20 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/management/employee/work_scheduler/ReceptionScheduler.java
> +                            long minutes = Duration.between(time.getTime(), clientGroup.getCheckOutTime()).toMinutes();
to tak samo można wrzucić do utils

2023-08-14 16:20 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/management/employee/work_scheduler/WorkScheduler.java
> +        if (entitiesToExecuteService.size() == 1) {
tak teraz myśle że może warto owrapować ten condition przez jakąś fukcję żeby było wiadomo dokładnie dlaczego tu jest == 1

2023-08-14 16:20 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/engine/Engine.java
> +        timeCommandExecutor.addCommand(time.getTime(),new RepeatingTimeCommand(EVERY_SHIFT, receptionScheduler::perShiftUpdate));
może warto zgrupować te komendy w grupy i wywoływać przyporządkowane fukcje np initiateEmployeeSchedule czy co kolwiek innego

2023-08-15 11:36 UTC, pwgacek commented on core/src/test/java/json/JSONDataLoaderTest.java
> +
racja. Jak myślisz wywalić te testy czy je jakoś zmodyfikować? Bo tutaj chciałem sprawdzić tylko czy się nie wywala po instacjonowaniu pól statycznych

2023-08-17 07:39 UTC, dudiiiiiiii commented
Jeśli chodzi o buildera to można też użyć tego z Lomboka (mniej kodu ale nie jestem pewien jak tam jest jeśli byś chciał żeby wszystkie pola były wymagane do danej klasy) bo ja pewnie i tak go dorzucę żeby sobie gettery i settery zrobić do hotel itp.

2023-08-17 07:39 UTC, dudiiiiiiii submitted a review, later dismissed

2023-08-18 06:14 UTC, lawos98 requested changes

2023-08-18 06:43 UTC, lawos98 approved these changes

2023-08-18 06:46 UTC, merged