change roomState to booleans
Hotel-Simulator/Hotel-Simulator pull request #12
Opened 2023-08-14 18:16 UTC by dudiiiiiiii

Room state changed from enum to 5 booleans

2023-08-14 18:53 UTC, lawos98 requested changes

2023-08-14 18:53 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/model/Room.java
> +// dopracuj troszkę nizej wartośc wzoru - rename standard for competitiveness
TODO jak zrobione do usunięcia jak nie to usunąć i task na jire

2023-08-14 18:53 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/model/Room.java
> +	private boolean upgrading;
Data klasa bo zbyt dużo się już pól robi

2023-08-14 18:53 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/model/Room.java
>  	public int getCapacity() {
jak jest final nie ma sensu gettera bo i tak nie możemy z nim nic więcej zrobić jak tylko odczytać

2023-08-14 18:53 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/model/Room.java
>  	public boolean upgradeRank() {
to raczej powino być void , a to sprawdzenie powino się odbywać w checku w osobnej funkcji , albo w ostateczności zmienić nazwę fukcji na coś pokroju tryUpgradeRank() bo nie sugeruje w ogóle że coś zwróci

2023-08-14 18:53 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/model/Room.java
> +	public boolean clean(){
ten sam case co wyżej

2023-08-14 18:53 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/model/Room.java
> -	public boolean fix() {
ten sam case co wyżej

2023-08-14 18:53 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/management/employee/CleaningScheduler.java
>  	};
nie ma sensu trzymać tego komentarza

2023-08-14 18:53 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/management/employee/CleaningScheduler.java
>  	private static final Comparator<Room> roomComparator = (o1, o2) -> {
całość da się uprościć do Boolean.compare(o2.isOccupied(), o1.isOccupied());

2023-08-14 18:58 UTC, lawos98 commented
brakuje jeszcze ogólnie testów do tego

2023-08-15 17:20 UTC, pwgacek requested changes

2023-08-22 17:50 UTC, pwgacek requested changes

2023-08-22 17:50 UTC, pwgacek commented on core/src/main/java/pl/agh/edu/model/RoomStates.java
> +public class RoomStates {
ja bym zmienił nazwe na RoomState

2023-08-22 17:50 UTC, pwgacek commented on core/src/main/java/pl/agh/edu/model/RoomStates.java
> +	public RoomStates(boolean isOccupied, boolean isDirty, boolean isFaulty, boolean isBeingUpgraded) {
nie widzę kiedy można by użyc tego konstruktora. Ja bym usunął

2023-08-22 17:50 UTC, pwgacek commented on core/src/main/java/pl/agh/edu/model/Room.java
>  	private BigDecimal marketPrice;
nigdy tego nie inicjujemy za to jedna metoda tego używa. To chyba problem

2023-08-22 17:50 UTC, pwgacek commented on core/src/main/java/pl/agh/edu/model/Room.java
>  	public BigDecimal getStandard() {
Co robi ta metoda? Nie powinno się uzywać przstarzałych metod

2023-08-22 17:50 UTC, pwgacek commented on core/src/main/java/pl/agh/edu/model/Hotel.java
> +			if (!room.getRoomStates().isOccupied() && !room.getRoomStates().isBeingUpgraded() && room.getRentPrice().compareTo(group.getDesiredPricePerNight()) < 1) {
Trzeba dodać sprawdzanie czy RoomRank jest taki jaki chcą klienci

2023-08-22 17:50 UTC, pwgacek commented on core/src/main/java/pl/agh/edu/model/Hotel.java
> +	public void addRoomByRank(Room room) {
nie powinno się dodawać metod zeby łatwiej się testowało. Polecam reflekcje

2023-08-22 17:50 UTC, pwgacek commented on core/src/test/java/model/HotelTest.java
> +	public void findRoomForClientGroupSuccessTest() {
powinny być sprawdzone też  Failury min. : brak pokoi bo są brudne, upgradowane, zbyt drogie albo zła ranga. Proponuję test parametryzowany

2023-08-28 14:45 UTC, pwgacek commented on core/src/main/java/pl/agh/edu/model/Room.java
>  	private BigDecimal marketPrice;
ja bym po prostu wywalił to pole

2023-08-28 14:54 UTC, pwgacek requested changes

2023-08-28 14:54 UTC, pwgacek commented on core/src/main/java/pl/agh/edu/model/Room.java
> +	private RoomState roomState;
dodałbym final (tak jak intellij podpowiada)

2023-08-28 14:54 UTC, pwgacek commented on core/src/main/java/pl/agh/edu/model/Hotel.java
> +				.filter(room -> !room.getRoomStates().isDirty() && !room.getRoomStates().isOccupied() && !room.getRoomStates().isBeingUpgraded() && room.getRentPrice().compareTo(
ja bym zrobił osobny filtr na kazdy warunek

2023-08-31 16:20 UTC, pwgacek approved these changes

2023-08-31 17:03 UTC, lawos98 requested changes

2023-09-01 15:11 UTC, lawos98 approved these changes

2023-09-01 15:11 UTC, lawos98 commented on core/src/test/java/model/HotelTest.java
> +	private final ClientGroup group = mock(ClientGroup.class);
wczoraj przegadaliśmy że zostawiamy same adnotacje bez instancjonowania,  ale spoko poźniej zrobię refactor wszystkiego to podmienię

2023-09-01 16:54 UTC, merged