HS-263 | list rooms aggregated by size and rank
Hotel-Simulator/Hotel-Simulator pull request #124
Opened 2023-11-28 11:39 UTC by dudiiiiiiii

2023-11-28 21:35 UTC, lawos98 commented on assets/i18n/language_en.properties
> +roomTable.column.icon = Icon
chyba bardziej byłbym przekonany za jakiś zdjęciem niż ikoną ale up to you

2023-11-28 21:45 UTC, lawos98 commented on assets/i18n/language_pl.properties
> +roomTable.column.icon = Icona
po polsku się tak piszę? xD

2023-11-28 21:45 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/ui/frame/room/RoomFrame.java
> +		return createCustomLabel(engine.roomManager.roomPricePerNight.getPrice(room) + "$");
wyciągnał bym do pola roomManagera

2023-11-29 16:35 UTC, pwgacek requested changes

2023-11-29 16:35 UTC, pwgacek commented on core/src/main/java/pl/agh/edu/engine/room/Room.java
> +	public RoomSize getSize() {
potrzebujemy getera do pola który jest public final?

2023-11-29 16:35 UTC, pwgacek commented on core/src/main/java/pl/agh/edu/engine/room/RoomManager.java
> +				.filter(room -> room.getRank().equals(rank) && room.getSize().equals(size))
enumy można porównywać przy użyciu "=="

2023-11-30 21:39 UTC, lawos98 approved these changes

2023-12-01 13:30 UTC, merged