HS-177
Hotel-Simulator/Hotel-Simulator pull request #18
Opened 2023-08-27 16:38 UTC by pwgacek

2023-08-27 20:29 UTC, lawos98 requested changes

2023-08-27 20:29 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/model/Room.java
> +	public void upgradeRank(RoomRank desiredRank) {
odnośnie ulepszeń spoko jakby była jakaś metoda czy można ten pokój ulepszyć żeby później np wyłącząć przycisk na frontEndzie

2023-08-28 14:11 UTC, dudiiiiiiii approved these changes

2023-09-03 12:13 UTC, lawos98 approved these changes

2023-09-03 18:55 UTC, merged