HS-183 | BankAccount & Credit refactor
Hotel-Simulator/Hotel-Simulator pull request #30
Opened 2023-09-13 14:03 UTC by pwgacek

2023-09-13 18:02 UTC, lawos98 requested changes

2023-09-13 18:02 UTC, lawos98 commented on assets/jsons/bank_config.json
> +
troszkę dziwna jest ta pusta linia

2023-09-13 18:09 UTC, pwgacek commented on core/src/main/java/pl/agh/edu/engine/Engine.java
> +	private final BankAccount bankAccount = new BankAccount(new BigDecimal("0.05"), BigDecimal.valueOf(2));
to jest bardzo dobre pytanie. Jeśli chcemy zapisać do BigDecimal liczbę nie całkowitą to najlepiej to zrobić z użyciem stringa bo jakbyśmy użyli double dla np 0.05 to mogło by się zapisać 0.05000000001. Z wartościami całkowitymi nie ma takiego problemu więc można uzywać metody statycznej valueOf()

2023-09-13 18:11 UTC, pwgacek commented on core/src/main/java/pl/agh/edu/model/bank/Credit.java
> +	private final BankAccount bankAccount;
nie rozumiem

2023-09-13 19:45 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/engine/Engine.java
> +	private final BankAccount bankAccount = new BankAccount(new BigDecimal("0.05"), BigDecimal.valueOf(2));
w sensie ogarniam tą sprawę,ale bardziej pytanie żeby zachować konsystentość bo rozumiem że to się tak samo wykrzaczy jeżeli przekroczymy longa w valueOf. i po prostu wszędzie korzystać z parsowania ze stringa

2023-09-13 19:48 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/model/bank/Credit.java
> +	private final BankAccount bankAccount;
w sensie pojawia nam się cykl w zależnościach pomiędzy klasami, BankAccount trzyma wszystkie swoje kredyty w liście, a każdy element tej listy też trzyma nawiązanie do BankAccount w którym się znajduję i czy pojawi się jakiś case że będziemy mieć kredyt ale nie bedziemy mieć BankAccount w którym się to znajduje?

2023-09-13 19:51 UTC, lawos98 requested changes

2023-09-13 19:51 UTC, lawos98 commented on core/src/test/java/model/bank/CreditTest.java
> +		bankAccount = mock(BankAccount.class);
tu wystarczy to raz usawić przed @BeforeEach jako zwykłe pole w klasie, nie ma potrzeby jego aktualizowania

2023-09-13 19:51 UTC, lawos98 commented on core/src/test/java/time/NRepeatingTimeCommandTest.java
> +		Runnable runnable = mock(Runnable.class);
tak jak w wcześniej

2023-09-13 20:22 UTC, pwgacek commented on core/src/main/java/pl/agh/edu/model/bank/Credit.java
> +	private final BankAccount bankAccount;
nie będzie

2023-09-13 21:01 UTC, lawos98 commented on core/src/test/java/time/NRepeatingTimeCommandTest.java
> -		Runnable runnable = mock(Runnable.class);
sorki powalilo mi się poprawna forma to 
```	
@Mock
private static Runnable `runnable; 
```

2023-09-14 16:46 UTC, lawos98 approved these changes

2023-09-16 09:16 UTC, lawos98 approved these changes

2023-09-16 09:21 UTC, merged