HS-34 | poziom trudności, scenariusze, funkcja popularności
Hotel-Simulator/Hotel-Simulator pull request #31
Opened 2023-09-13 15:41 UTC by dudiiiiiiii

2023-09-13 17:58 UTC, pwgacek requested changes

2023-09-13 17:58 UTC, pwgacek commented on assets/jsons/hotel_scenarios_config.json
> +  "visit_probabilities": {
trzeba wywalić visit probabilities z client_config

2023-09-13 17:58 UTC, pwgacek commented on assets/jsons/hotel_scenarios_config.json
> +  "difficulty_multiplier": {
to chyba nie ma związku ze scenariuszami, ja bym przeniósł do game_config

2023-09-13 17:58 UTC, pwgacek commented on core/src/main/java/pl/agh/edu/management/hotel/HotelScenariosManager.java
> +	private HashMap<Pair<Integer, Integer>, Double> seasonalMultiplier;
a nie lepiej użyć tego? https://docs.oracle.com/javase/8/docs/api/java/time/MonthDay.html

2023-09-13 17:58 UTC, pwgacek commented on core/src/main/java/pl/agh/edu/management/hotel/HotelScenariosManager.java
> +	private double difficultyMultiplier;
wg mnie scenariusze hotelu nie są powiązane w poziomem trudności więc powinny być w osobnych klasach

2023-09-13 17:58 UTC, pwgacek commented on core/src/main/java/pl/agh/edu/model/HotelPopularityFunction.java
> +			for (Integer key : Arrays.asList(1, 3, 5, 7, 8, 10, 12)) {
streamy

2023-09-13 17:58 UTC, pwgacek commented on core/src/main/java/pl/agh/edu/model/HotelPopularityFunction.java
> +				for (Integer key : Arrays.asList(4, 6, 9, 11)) {
stream

2023-09-18 20:55 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/management/hotel/HotelScenariosManager.java
> +	public HotelScenariosManager() {
chyba lepiej i wygodniej było by po prostu podawać scenario jako parametr konstruktora

2023-09-18 20:55 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/management/game/GameDifficultyManager.java
> +	public GameDifficultyManager() {
chyba lepiej i wygodniej było by po prostu podawać poziom trudności jako parametr konstruktora

2023-09-18 20:55 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/management/hotel/HotelScenariosManager.java
> +		return seasonalMultiplier.get(MonthDay.of(month, day));
chyba lepiej już dorobić sobie metodę w "time" aby zwracała nam ten typ

2023-09-18 20:55 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/model/HotelPopularityFunction.java
> +	public static HashMap<MonthDay, Double> getSeasonalMultipliers(HotelType hotelType) {
luzny pomysł rozdzielić tą fukcje na mniejsze prywatne bo trochę nie wiadomo co tu się dzieje odrazu

2023-09-18 20:55 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/model/HotelPopularityFunction.java
> +			if (i < 28)
spoko jak używamy nawiasów w ten sposób a nie przy i<30 używamy a przy i<28 nie

2023-09-19 17:35 UTC, pwgacek requested changes

2023-09-19 17:35 UTC, pwgacek commented on core/src/main/java/pl/agh/edu/model/HotelPopularityFunction.java
> +	public static HashMap<MonthDay, Double> getSeasonalMultipliers(HotelType hotelType) {
zrob zeby funkcja zwracała Mape

2023-09-19 17:35 UTC, pwgacek commented on core/src/main/java/pl/agh/edu/management/hotel/HotelScenariosManager.java
> +	private HashMap<MonthDay, Double> seasonalMultiplier;
Nie lepiej zadeklarować jako mape?

2023-09-23 06:43 UTC, pwgacek commented on core/src/main/java/pl/agh/edu/model/time/Time.java
> +	public MonthDay getCurrentMonthDay() {
ja bym bez nazwał getMonthDay. (skoro pytamy czas o dzień to raczej będzie to obecny)

2023-09-23 06:44 UTC, pwgacek commented on core/src/main/java/pl/agh/edu/model/time/Time.java
> +	public MonthDay getCurrentMonthDay() {
Dopisz test do tej metody

2023-09-23 06:47 UTC, pwgacek requested changes

2023-09-23 06:47 UTC, pwgacek commented on core/src/main/java/pl/agh/edu/model/time/Time.java
> +	public MonthDay getCurrentMonthDay() {
ja bym usunął current bo wiadomo że chodzi o obecny dzień

2023-09-23 06:47 UTC, pwgacek commented on core/src/main/java/pl/agh/edu/model/time/Time.java
> +	public MonthDay getCurrentMonthDay() {
test do tego trzeba dodać

2023-09-23 10:03 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/model/HotelPopularityFunction.java
> +	private static PolynomialSplineFunction getSplineFunction(HotelType hotelType) {
to bym tak samo jeszcze podzielił na mniejsze częsci coś w stylu (nie wiem czy to będzie działać )
```java 
private static PolynomialSplineFunction getSplineFunction(HotelType hotelType) {
    Map<Integer, Double> monthClientsMultiplier = JSONHotelScenariosDataLoader.vacationPopularity.get(hotelType);
    double[] x = generateXValues();
    double[] y = generateYValues(monthClientsMultiplier);
    
    return createSplineFunction(x, y);
}

private static double[] generateXValues() {
    return IntStream.rangeClosed(0, 13)
            .asDoubleStream()
            .toArray();
}

private static double[] generateYValues(Map<Integer, Double> monthClientsMultiplier) {
    return IntStream.range(0, 14)
            .mapToDouble(i -> calculateYValue(monthClientsMultiplier, i))
            .toArray();
}

private static double calculateYValue(Map<Integer, Double> monthClientsMultiplier, int i) {
    int month = (i % 12) + 1;
    return monthClientsMultiplier.getOrDefault(month, 0.0);
}

private static PolynomialSplineFunction createSplineFunction(double[] x, double[] y) {
    SplineInterpolator interpolator = new SplineInterpolator();
    return interpolator.interpolate(x, y);
}
```

2023-09-23 13:25 UTC, pwgacek approved these changes

2023-09-23 13:25 UTC, lawos98 approved these changes

2023-09-23 13:26 UTC, merged