HS-196 | Refactor of Rating component
Hotel-Simulator/Hotel-Simulator pull request #45
Opened 2023-09-26 14:55 UTC by lawos98

2023-09-26 18:44 UTC, jagodek requested changes
Tak jak sobię teraz myślę to przydałaby się opcja disabled. Żeby komponent po prostu wyświetlał rating... I też jakiś setter skoro ma wyświetlać

2023-09-28 06:36 UTC, jagodek requested changes
Sugeruję te podmianki bo disabled działa na opak. I nie wiem czy to celowy zamiar ale funkcja dalej się odpala przy disabled. I nie wiem czy consumer powinien się też odpalać podczas setDefaultRating - chodzi o wychodzenie z obszaru gwiazdki.

2023-09-28 06:36 UTC, jagodek commented on core/src/main/java/pl/agh/edu/actor/component/rating/Rating.java
> +	private boolean disabled = true;
```suggestion
	private boolean disabled = false;
```

2023-09-28 06:36 UTC, jagodek commented on core/src/main/java/pl/agh/edu/actor/component/rating/Star.java
> +				return rating.isDisabled();
```suggestion
				return !rating.isDisabled();
```

2023-09-28 06:36 UTC, jagodek commented on core/src/main/java/pl/agh/edu/actor/component/rating/Star.java
> +				if (rating.isDisabled())
```suggestion
				if (!rating.isDisabled())
```

2023-09-28 06:36 UTC, jagodek commented on core/src/main/java/pl/agh/edu/actor/component/rating/Rating.java
> +		function.accept(rating);
```suggestion
if(!isDisabled())
		function.accept(rating);
```

2023-09-28 16:18 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/actor/component/rating/Rating.java
> +		function.accept(rating);
tutaj się nie zgodzę trochę ustawienie wartości ratingu nie powino zależeć czysto od tego czy możemy w niego klikać czy też nie

2023-09-28 19:04 UTC, jagodek approved these changes
ok

2023-09-28 19:52 UTC, jagodek commented on core/src/main/java/pl/agh/edu/actor/component/rating/Rating.java
> +		this.setSize(RatingStyle.getWidth(), RatingStyle.getHeight());
JESZCZE JEDNO NA KONIEC. to chyba nie ma wpływu na rozmiar tabeli. Jak do tej pory udawało mi się ustaliź rozmiar ustawiać przez to opakowanie w inną tabelę i ustawienie długości/wysokości przez add().width().height()

2023-09-28 20:07 UTC, jagodek commented on core/src/main/java/pl/agh/edu/actor/component/rating/Rating.java
> +		this.setSize(RatingStyle.getWidth(), RatingStyle.getHeight());
The default behavior of Table is to size all children to their minimum size. You must remember that when you use Table, you no longer set the dimensions of the widget directly. You set the size of the cell, then the cell sizes the contents. Do not use setWidth() or setHeight().

2023-09-30 09:03 UTC, merged