HS-195 | initial balance difficulty
Hotel-Simulator/Hotel-Simulator pull request #46
Opened 2023-09-26 17:00 UTC by dudiiiiiiii

## Pull reviewers stats
Stats for the last 365 days:
|                                                                                                                                                                 | User               | Total reviews   | Median time to review | Total comments   |
| --------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------ | --------------- | --------------------- | ---------------- |
| <a href="https://github.com/lawos98"><img src="https://avatars.githubusercontent.com/u/85324038?u=f7c1da89ab9c45271cc8493559c3e40cc89ef21b&v=4" width="32"></a> | lawos98<br/>🥇     | **20**<br/>▀▀▀▀ | 21h 15m<br/>▀▀        | **88**<br/>▀▀▀▀▀ |
| <a href="https://github.com/pwgacek"><img src="https://avatars.githubusercontent.com/u/80721230?v=4" width="32"></a>                                            | pwgacek<br/>🥈     | 13<br/>▀▀       | 2d 8h 51m<br/>▀▀▀▀▀   | 65<br/>▀▀▀▀      |
| <a href="https://github.com/dudiiiiiiii"><img src="https://avatars.githubusercontent.com/u/79313233?v=4" width="32"></a>                                        | dudiiiiiiii<br/>🥉 | 14<br/>▀▀       | 21h 44m<br/>▀▀        | 6<br/>           |
| <a href="https://github.com/jagodek"><img src="https://avatars.githubusercontent.com/u/92532760?v=4" width="32"></a>                                            | jagodek<br/>       | 10<br/>▀▀       | **8h 44m**<br/>▀      | 4<br/>           |

**TOTALS | PRs**: 38. **Comments:** 163. **Time to review:** 22h 42m

2023-09-30 06:20 UTC, pwgacek requested changes

2023-09-30 06:20 UTC, pwgacek commented on assets/jsons/game_config.json
> +  "initial_balance": {
ja bym zrobił 500tys -> 200tys -> 100tys ->50tys

2023-09-30 06:20 UTC, pwgacek commented on core/src/main/java/pl/agh/edu/json/data_loader/JSONGameDataLoader.java
> +	public static EnumMap<DifficultyLevel, Long> initialBalance;
dlaczego nie EnumMap<DifficultyLevel, BigDecimal> ?

2023-09-30 06:20 UTC, pwgacek commented on core/src/main/java/pl/agh/edu/model/bank/BankAccount.java
> +		this.balance = GameDifficultyManager.getInstance().getInitialBalance();
ja bym przyjmował przez konstruktor ten initialBalance

2023-09-30 16:52 UTC, lawos98 requested changes

2023-09-30 16:52 UTC, lawos98 commented on core/src/test/java/management/GameDifficultyManagerTest.java
> +		System.out.println(gameDifficultyManager.getDifficultyMultiplier());
potrzebny nam ten print tutaj?

2023-09-30 16:52 UTC, lawos98 commented on core/src/test/java/model/bank/BankAccountTest.java
> +			throws ReflectiveOperationException {
tutaj się coś linter wywalił czy dlaczego jest takie formatowanie?

2023-10-02 05:26 UTC, dudiiiiiiii commented on core/src/test/java/model/bank/BankAccountTest.java
> +			throws ReflectiveOperationException {
Zmieniłem formatowanie ale metodę narazie zostawiłem póki na main'e nie ma zmian Pawła bo testy by mi nie przechodzły jakbym usunął całą metodę tak jak wczoraj mówiłem

2023-10-02 17:35 UTC, pwgacek commented on assets/jsons/game_config.json
> +  "initial_balance": {
ja bym to wstawił do bank_config ale to tylko sugestia, tutaj też może być

2023-10-02 18:03 UTC, pwgacek commented on core/src/test/java/model/bank/BankAccountTest.java
> +	public void setUp() throws ReflectiveOperationException {
dlaczego tu jest throws?

2023-10-02 18:05 UTC, pwgacek requested changes

2023-10-02 18:05 UTC, pwgacek commented on core/src/test/java/model/bank/BankAccountTest.java
> +	public void setUp() throws ReflectiveOperationException {
dlaczego tu jest throws?

2023-10-05 11:39 UTC, pwgacek approved these changes

2023-10-06 14:31 UTC, lawos98 approved these changes

2023-10-06 15:45 UTC, merged