HS-205 | Event Refactor part 1
Hotel-Simulator/Hotel-Simulator pull request #53
Opened 2023-10-06 15:47 UTC by pwgacek

2023-10-09 18:55 UTC, pwgacek commented on assets/jsons/event_config.json
> +    "calendar_description": "Summer Holidays startPrepare yourself for an increased number of customers during this period!",
no to będzie robione w Event Refactor part 2

2023-10-12 08:51 UTC, pwgacek commented on assets/jsons/event_config.json
> +    "calendar_description": "Summer Holidays startPrepare yourself for an increased number of customers during this period!",
jednak nie będzie part 2 - tutaj dodałem tłumaczenia

2023-10-12 19:25 UTC, lawos98 requested changes

2023-10-12 19:25 UTC, lawos98 commented on assets/i18n/language_pl.properties
> +randomEvent.sportTournament.eventAppearancePopupDescription =  Niedługo, bo [date] w naszym miescie rozpocznie się turniej sportowy. Będzie on trwał [noDays] dni. Przygotuj się na zwiększoną ilość kl
*mieście

2023-10-12 19:25 UTC, lawos98 commented on assets/i18n/language_pl.properties
> +randomEvent.sportTournament.eventStartPopupDescription = W naszym miescie rozpoczął się turniej sportowy! Będzie on trwał [noDays] dni. Spodziewaj się większej ilości klientów.
same as above

2023-10-12 19:25 UTC, lawos98 commented on assets/i18n/language_pl.properties
> +randomEvent.businessConference.eventAppearancePopupDescription =  Niedługo, bo [date] w naszym miescie rozpocznie się konferencja biznesowa. Będzie ona trwała [noDays] dni. Przygotuj się na zwiększon
same as below

2023-10-12 19:25 UTC, lawos98 commented on assets/i18n/language_pl.properties
> +randomEvent.fair.eventAppearancePopupDescription =  Niedługo, bo [date] w naszym miescie rozpocznie się jarmark. Będzie on trwał [noDays] dni. Przygotuj się na zwiększoną ilość klientów w tym okresie
same as below

2023-10-12 19:25 UTC, lawos98 commented on assets/i18n/language_pl.properties
> +randomEvent.musicFestival.eventAppearancePopupDescription =  Niedługo, bo [date] w naszym miescie rozpocznie się festiwal muzyczny. Będzie on trwał [noDays] dni. Przygotuj się na zwiększoną ilość kli
same as below

2023-10-12 19:25 UTC, lawos98 commented on assets/i18n/language_pl.properties
> +randomEvent.scientificConference.eventAppearancePopupDescription =  Niedługo, bo [date] w naszym miescie rozpocznie się konferencja naukowa. Będzie ona trwała [noDays] dni. Przygotuj się na zwiększon
same as below

2023-10-12 19:25 UTC, lawos98 commented on assets/i18n/language_pl.properties
> +randomEvent.fair.eventAppearancePopupDescription =  Niedługo, bo [date] w naszym miescie rozpocznie się jarmark. Będzie on trwał [noDays] dni. Przygotuj się na zwiększoną ilość klientów w tym okresie
zmienił by tu trochę szyk na " Niedługo, bo 9 sierpnia rozpocznie się jarmark w naszym mieście" ale jak uważasz

2023-10-12 19:25 UTC, lawos98 commented on assets/i18n/language_pl.properties
> +cyclicEvent.winterVacation.eventAppearancePopupDescription = Już niedługo, bo 1 stycznia rozpoczną się ferie zimowe! Przygotuj się na zwiększoną ilość klientow!
* klientów

2023-10-12 19:25 UTC, lawos98 commented on assets/i18n/language_pl.properties
> +cyclicEvent.summerVacation.eventAppearancePopupDescription = Już niedługo, bo 1 lipca rozpoczną się wakacje! Przygotuj się na zwiększoną ilość klientow!
same as above

2023-10-12 19:25 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/GdxGame.java
> +		Engine engine = new Engine();
jak już to lepiej żeby było jako pole poza konstruktorem ale czaję fażę że pewnie żeby testować

2023-10-12 19:25 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/management/event/EventHandler.java
> +					System.out.println(event);
print

2023-10-13 08:20 UTC, dudiiiiiiii commented on assets/i18n/language_pl.properties
> +cyclicEvent.summerVacation.eventAppearancePopupDescription = Już niedługo, bo 1 lipca rozpoczną się wakacje! Przygotuj się na zwiększoną ilość klientow!
Ja też się do polskiego przyczepię powinna być raczej liczba a nie ilość - na zwiększoną liczbę klientów

2023-10-13 08:31 UTC, dudiiiiiiii commented on core/src/test/java/json/JSONDataLoaderTest.java
> +			// List<CyclicEventData> cyclicEventData = JSONEventDataLoader.cyclicEventData;
Czemu tu takie komentarze zostały?

2023-10-16 13:59 UTC, dudiiiiiiii submitted a review, later dismissed

2023-10-16 16:36 UTC, dudiiiiiiii approved these changes

2023-10-16 17:48 UTC, lawos98 approved these changes

2023-10-16 17:54 UTC, merged