HS-212 | Uzależnić attractiveness_constants od scenariusza
Hotel-Simulator/Hotel-Simulator pull request #61
Opened 2023-10-11 07:53 UTC by pwgacek

2023-10-12 16:20 UTC, lawos98 requested changes

2023-10-12 16:20 UTC, lawos98 commented on core/src/test/java/json/JSONDataLoaderTest.java
> +import pl.agh.edu.enums.*;
wild card'om mówimy nie 😜

2023-10-12 18:59 UTC, lawos98 submitted a review, later dismissed

2023-10-13 09:01 UTC, dudiiiiiiii commented on core/src/main/java/pl/agh/edu/management/hotel/HotelScenariosManager.java
> +	public AttractivenessConstantsData getAttractivenessConstants() {
Jakby mozna było przenieść to trochę niżej niż atrybuty( zakładam że generowałeś z intellij i tam wrzuciło)

2023-10-16 14:10 UTC, dudiiiiiiii submitted a review, later dismissed

2023-10-16 17:46 UTC, lawos98 submitted a review, later dismissed

2023-10-17 07:25 UTC, lawos98 approved these changes

2023-10-17 07:26 UTC, merged