HS-210 | Możliwość zmiany shiftu / wynagrodzenia pracownika
Hotel-Simulator/Hotel-Simulator pull request #63
Opened 2023-10-17 08:41 UTC by pwgacek

2023-10-20 17:03 UTC, lawos98 requested changes

2023-10-20 17:03 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/model/employee/Employee.java
> +	public ContractOfferResponse offerNewContract(ContractOffer contractOffer) {
bardziej subiektywna opinia
ale dla mnie takie drzewo if słabo wygląda i czy nie lepiej było by coś w tym rodzaju
```java
int offerShift = contractOffer.shift();
BigDecimal offeredWage = contractOffer.offeredWage();

boolean isPositive = (offerShift == shift && offeredWage.compareTo(wage) > 0) ||
                     (offerShift == preferences.desiredShift && offeredWage.compareTo(preferences.acceptableWage) >= 0) ||
                     (offerShift != preferences.desiredShift && offeredWage.compareTo(preferences.desiredWage) >= 0);

return isPositive ? ContractOfferResponse.POSITIVE : ContractOfferResponse.NEGATIVE;
```

2023-10-20 17:03 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/model/employee/PossibleEmployee.java
> +	public ContractOfferResponse offerJob(ContractOffer contractOffer) {
same case as above

2023-10-20 19:35 UTC, lawos98 approved these changes

2023-10-21 13:14 UTC, dudiiiiiiii approved these changes

2023-10-21 13:16 UTC, merged