HS-217 | Dodano komentarze do opiniii
Hotel-Simulator/Hotel-Simulator pull request #82
Opened 2023-10-26 19:15 UTC by pwgacek

2023-10-27 14:06 UTC, lawos98 requested changes

2023-10-27 14:06 UTC, lawos98 commented on assets/i18n/language_en.properties
> +opinionComment.steppedOutOfQueue = The queue at the reception was too long!
dodać jakiś jeszcze jeden wymiar np negative czy coś w tym stylu

2023-10-27 14:06 UTC, lawos98 commented on assets/i18n/language_pl.properties
> +opinionComment.steppedOutOfQueue = Zbyt długa kolejka do recepcji!
same as above

2023-10-27 14:06 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/engine/generator/ClientGenerator.java
> +	private static final Faker faker = new Faker();
czy w tym przypadku będziemy mieli ogranę sprawę nazw które będą łatwo tłumaczone na inne języki

2023-10-27 14:06 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/engine/generator/ClientGenerator.java
> +	private static final Faker faker = new Faker();
może lepiej było być mieć jakieś permutację dwóch list do których będziemy mieli przygotowane tłumaczenie per jezyk

2023-10-27 14:06 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/engine/opinion/OpinionData.java
> +        List<LanguageString> comments
może warto tu set wprowadzić na zaś

2023-10-29 11:22 UTC, pwgacek commented on core/src/main/java/pl/agh/edu/engine/generator/ClientGenerator.java
> +	private static final Faker faker = new Faker();
pytanie czy my chcemy tłumaczyć imiona bo wg mnie powinniśmy ustalić jedną wersje: albo będą angielskie albo polskie i ich nie tłumaczyć.

2023-10-29 11:24 UTC, pwgacek commented on assets/i18n/language_pl.properties
> +opinionComment.employeesSatisfaction.good = Obsługa była bardzo miła!
wg mnie nikt nie pisze komentarzy ze obłsuga była neutralna

2023-10-29 11:26 UTC, pwgacek commented on assets/i18n/language_en.properties
> +opinionComment.roomPrice.low = The price was surprisingly low.
wg mnie w opiniach albo pojawiają się info ze cena była zbyt drogra albo niska a nie że w sam raz - jak ktoś nie ma uwag co do ceny to raczej nie będzie o tym pisał

2023-10-29 11:55 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/engine/generator/ClientGenerator.java
> +	private static final Faker faker = new Faker(new Locale("pl-PL"));
co w takim razie z angielskimi imieniami?

2023-10-29 11:57 UTC, lawos98 commented on core/src/main/java/pl/agh/edu/engine/generator/ClientGenerator.java
> +	private static final Faker faker = new Faker();
dla mnie najlepszym sposobem zrobić jakiegoś matrixa 100 x 100 z imieniami i nazwiskami które możemy tłumaczyć na dowolny jezyk

2023-10-29 13:03 UTC, lawos98 approved these changes

2023-10-29 14:15 UTC, dudiiiiiiii approved these changes

2023-10-29 14:18 UTC, merged